include(ExternalProject)

set(OpenImageIO_GIT_REPOSITORY "https://github.com/AcademySoftwareFoundation/OpenImageIO.git")
set(OpenImageIO_GIT_TAG "master")

set(OpenImageIO_ARGS
    ${toucan_EXTERNAL_PROJECT_ARGS}
    -DOIIO_BUILD_TESTS=OFF
    -DOIIO_BUILD_TOOLS=OFF
    -DOIIO_BUILD_DOCS=OFF
    -DOIIO_INSTALL_DOCS=OFF
    -DOIIO_INSTALL_FONTS=OFF
    -DUSE_PNG=ON
    -DUSE_BZIP2=OFF
    -DUSE_DCMTK=OFF
    -DUSE_FFMPEG=OFF
    -DUSE_FREETYPE=OFF
    -DUSE_GIF=OFF
    -DUSE_JXL=OFF
    -DUSE_LIBHEIF=OFF
    -DUSE_LIBRAW=OFF
    -DUSE_NUKE=OFF
    -DUSE_OPENCOLORIO=OFF
    -DUSE_OPENCV=OFF
    -DUSE_OPENJPEG=OFF
    -DUSE_OPENVDB=OFF
    -DUSE_PTEX=OFF
    -DUSE_PYTHON=OFF
    -DUSE_QT=OFF
    -DUSE_TBB=OFF
    -DUSE_WEBP=OFF)

ExternalProject_Add(
    OpenImageIO
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/OpenImageIO
    DEPENDS TIFF PNG libjpeg-turbo OpenEXR
    GIT_REPOSITORY ${OpenImageIO_GIT_REPOSITORY}
    GIT_TAG ${OpenImageIO_GIT_TAG}
    CMAKE_ARGS ${OpenImageIO_ARGS})
